name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["29.3", "30.1"]
    container:
      image: silex/emacs:${{ matrix.emacs_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install git and make
        run: |
          apt-get update -y
          apt-get install -y git make
      - name: Install Cask
        run: |
          git clone --depth 1 https://github.com/cask/cask
          make -C cask install
      - name: Run tests
        run: ./scripts/run-tests.sh
